--- #YAML:1.0
name: URI-Find-Iterator
version: 0.6
license: perl
distribution_type: module
requires:
  Test::More: 0
  UNIVERSAL::require: 0
  URI::Find: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  URI::Find::Iterator:
    file: lib/URI/Find/Iterator.pm
    version: 0.6
generated_by: Module::Build version 0.21
